version: "3.7"
services:
    # This db is just for local development.
    portfolio-postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: portfolio
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - 5432:5432
        volumes:
            - ./persistence/postgres:/var/lib/postgresql/data
        container_name: portfolio-postgres

    # Strapi instance for local dev
    portfolio-strapi:
        build: .
        image: portfolio-strapi:latest
        ports:
            - 1337:1337
        volumes:
            - ./persistence/strapi:/srv/app
        depends_on:
            - portfolio-postgres
        container_name: portfolio-strapi